name: Periodic Hello

on:
  workflow_run:
    workflows: [Deployment Pipeline]
    types:
      - completed
  workflow_dispatch:
  schedule:
    - cron: "25  10 * * *"

jobs:
  health_check:
    if: |
      github.event_name != 'workflow_run' ||
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello!"
      - name: Check for crash in patch
        uses: jtalk/url-health-check-action@e7d5ebdc9027fbf494d2d034f3e8fc78f8b7a2b9
        with:
          url: https://ci-cd-3kyn.onrender.com/error
