name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Run npm test
        run: npm run test
      - name: Run npm build
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' }}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Bump version and push tag
        if: |
          (github.event_name == 'push') &&
          (!contains(join(toJson(github.event.commits.*.message), ', '), '#skip'))
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
  discord_log:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: GITHIN LOG
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: deployment successful
        if: (github.event_name == 'push')
        uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: ":white_check_mark: **Deployment Successful!** A new version deployed to production"
          description: |
            [Deployment Details](${{github.event.repository.html_url}}/actions/runs/${{github.run_id}})
            **Commit:** ${{ github.event.after}}
            **Message:** ${{ github.event.commits[0].message}}
            **Author:** ${{ github.event.head_commit.author.name}}
      - name: deployment failed
        if: needs.simple_deployment_pipeline.result == 'failure'
        uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708

        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: ":x: **Build Failed!** The pipeline encountered an error"
          title: "**Failure Details**"
          status: failure
          color: #FF0000
          description: |
            **Repository:** ${{ github.repository}}
            **Branch:** ${{ github.ref_name }}
            **Commit:** ${{ github.sha }}
            **Message:** ${{ github.event.commits[0].message }}
            **Author:** ${{ github.actor }}
            **Workflow:** ${{ github.workflow}}
            **Job:** ${{ github.job}}


            [View Commit](${{github.event.repository.html_url}}/commit/${{github.event.head_commit.id}})
            [View Workflow Run](${{github.event.repository.html_url}}/actions/runs/${{github.run_id}})
